[project]
name = "seedvr2_videoupscaler"
description = "SeedVR2 official ComfyUI integration: ByteDance-Seed's one-step diffusion-based video/image upscaling with memory-efficient inference"
version = "2.5.24"
authors = [
    {name = "numz"},
    {name = "adrientoupet"}
]
license = {file = "LICENSE"} 
classifiers = [
     "Operating System :: OS Independent"
]
dependencies = [
    "torch==2.4.0+cu121",
    "torchvision==0.19.0+cu121",
    "safetensors==0.7.0",
    "numpy",
    "tqdm",
    "psutil",
    "einops==0.7.0",
    "antlr4-python3-runtime==4.9.3",
    "omegaconf==2.3.0",
    "diffusers==0.29.1",
    "peft>=0.17.0",
    "rotary-embedding-torch==0.5.3",
    "opencv-python>=4.10.0.84",
    "gguf",
    "matplotlib==3.10.9",
    "beartype==0.22.9"
]

[project.urls]
Repository = "https://github.com/numz/ComfyUI-SeedVR2_VideoUpscaler"
Documentation = "https://www.youtube.com/@AInVFX"
"Bug Tracker" = "https://github.com/numz/ComfyUI-SeedVR2_VideoUpscaler/issues"
Forum = "https://github.com/numz/ComfyUI-SeedVR2_VideoUpscaler/discussions"

[tool.comfy]
PublisherId = "ainvfx"
DisplayName = "ComfyUI-SeedVR2_VideoUpscaler"
Icon = "https://raw.githubusercontent.com/numz/ComfyUI-SeedVR2_VideoUpscaler/refs/heads/main/docs/seedvr_logo.png"
includes = []

[tool.comfy.isolation]
can_isolate = true
share_torch = true
package_manager = "uv"
execution_model = "host-coupled"
share_torch_no_deps = [
    "einops",
    "antlr4-python3-runtime",
    "omegaconf",
    "opencv-python",
    "numpy",
    "av",
    "diffusers",
    "rotary-embedding-torch",
    "transformers",
    "tokenizers",
    "huggingface-hub",
    "safetensors",
    "mediapy",
    "ipython",
    "matplotlib",
    "beartype",
]
